version: '3.8'
services:
  api-ats-market-clean-architecture:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DB_NAME
      - BASE_URL_API
      - JWT_SECRET
      - EMAIL_FROM
      - EMAIL_PASSWORD
      - URL_CONFIRMATION
      - URL_RESET
    networks:
      - pgvector_default

networks:
  pgvector_default:
    external: true